version: "3.8"

services:
  web_server:
    build: .
    command: python manage.py runserver 0.0.0.0:8600
    volumes:
      - .:/WebServer
    ports:
      - "8600:8600"
    expose:
      - "8600"
    networks:
      external-nw:
        ipv4_address: 172.18.0.6

networks:
  external-nw:
    external: true