version: "3.8"

services:
  login_db:
    image: "postgres:11"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5400:5400"
    command: -p 5400
    networks:
      - internal-login-server

  login_server:
    build: .
    command: python manage.py runserver 0.0.0.0:8200
    volumes:
      - .:/LoginServer
    ports:
      - "8200:8200"
    expose:
      - "8200"
    depends_on:
      - login_db
    networks:
      external-nw:
        ipv4_address: 172.18.0.3
      internal-login-server:


networks:
  internal-login-server:
    name: internal-login-server
    internal: true

  external-nw:
    external: true