version: "3.8"
   
services:
  main_db:
    image: "postgres:11"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5410:5410"
    command: -p 5410
  main_server:
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/MainServer
    ports:
      - "8100:8100"
    depends_on:
      - main_db
