version: "3.8"
   
services:
  db:
    image: "postgres:11"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  main_server:
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/MainServer
    ports:
      - "8100:8100"
    depends_on:
      - db
