version: "3.8"

services:
  keycloak_db:
    image: postgres:11
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - internal-keycloak-server
  keycloak_server:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin123
    ports:
      - "8300:8080"
    expose:
      - "8300"
    depends_on:
      - keycloak_db

    networks:
      external-nw:
        ipv4_address: 172.18.0.4
      internal-keycloak-server:


networks:
  internal-keycloak-server:
    name: internal-keycloak-server
    internal: true

  external-nw:
    external: true